### ISSUE TITLE
How to test the RTTS dataset

### ISSUE THREAD

**Issue by XinjieXiao** [W-Jilly/frequency-compensated-diffusion-model-pytorch#1]
Dear author. Thank you for open-sourcing this excellent work. I noticed that in the code for inference(infer.py), it requires the ground truth (GT) image paths for the dataset. However, RTTS doesn't have such paths. May I ask how you conducted testing for RTTS?

**Comment by W-Jilly** [comment]
MUSIQ, NIQE are the metrics to evaluate real hazy images such as RTTS.  We use Pyqia toolbox to get performance.

**Comment by W-Jilly** [comment]
You don't need to. If you don't want to change the code, I suppose a walkaround is to create 'HR' and 'HR_hazy' but keep the same content (e.g. ln -s HR HR_hazy).
