### ISSUE TITLE
train dataset

### ISSUE THREAD

**Issue by bnufw** [W-Jilly/frequency-compensated-diffusion-model-pytorch#10]
请问训练数据集就是把ots和its放在一起吗，这两个数据集是同种类型吗，我下载下来的ots的depth map是mat格式的

**Comment by TianwenZhou** [comment]
Hi, our training set is synthesized from the ground truth image of OTS and ITS (yes, we combine them together) using the method stated in our paper. The depth we use to synthesize the training data is generated using pretrained weights from MonoDepth.

**Comment by bnufw** [comment]
是用MonoDepth来生成clean image的depth map，然后利用clean image和depth map做HazeAug生成hazy image吗？

**Comment by TianwenZhou** [comment]
Thank you for your letter, I will reply ASAP.BWTianwen Zhou

**Comment by TianwenZhou** [comment]
That's correct:) You may refer to our paper for more details in the HazeAug process.

**Comment by bnufw** [comment]
感谢您的讲解，最后，请问可以提供相应的数据集或者生成这些数据集的代码么？

**Comment by TianwenZhou** [comment]
The datasets can be downloaded from the link in the README document. And the code of the data synthesize process can be found in our repo:)
